### ISSUE TITLE
Address Sanitizer goes bananas when rendering Lottie animations

### ISSUE THREAD

**Issue by jacobsapps** [airbnb/lottie-ios#2059]
## Which Version of Lottie are you using?

Lottie 4.0.0

I ran my app with the Address sanitiser and it kept getting caught whenever I wanted to render one of my lottie views: 

```
0x000139ec38f8 is located 0 bytes to the right of 56-byte region [0x000139ec38c0,0x000139ec38f8)
allocated by thread T0 here:
    #0 0x1081323ac in __sanitizer_mz_malloc+0x88 (libclang_rt.asan_iossim_dynamic.dylib:arm64+0x3e3ac) (BuildId: c1b3f817a02631eaacbc21ec0f6a487a32000000200000000700000000000e00)
    #1 0x18015f4b4 in _malloc_zone_malloc+0x80 (libsystem_malloc.dylib:arm64+0x154b4) (BuildId: 345980a18f6932539e0db87f010671c932000000200000000700000000000f00)
    #2 0x18f579540 in swift_slowAlloc+0x38 (libswiftCore.dylib:arm64+0x2c1540) (BuildId: fd3c87bf2e2c31d1932435c5e6a9616232000000200000000700000000000f00)
    #3 0x18f5796fc in swift_allocObject+0x30 (libswiftCore.dylib:arm64+0x2c16fc) (BuildId: fd3c87bf2e2c31d1932435c5e6a9616232000000200000000700000000000f00)
    #4 0x18f2df96c in _allocateUninitializedArray<A>(_:)+0x48 (libswiftCore.dylib:arm64+0x2796c) (BuildId: fd3c87bf2e2c31d1932435c5e6a9616232000000200000000700000000000f00)
    #5 0x101101b84 in static CGColorRef.rgb(_:_:_:)+0x378 (Gener8:arm64+0x100f31b84) (BuildId: 47c5cae9c1e035229d9ee05204332cfd32000000300000000700000000000f00)
    #6 0x101102ffc in static CGColorRef.rgba(_:_:_:_:)+0x3a0 (Gener8:arm64+0x100f32ffc) (BuildId: 47c5cae9c1e035229d9ee05204332cfd32000000300000000700000000000f00)
    #7 0x1011560cc in LottieColor.cgColorValue.getter+0x2d0 (Gener8:arm64+0x100f860cc) (BuildId: 47c5cae9c1e035229d9ee05204332cfd32000000300000000700000000000f00)
    #8 0x100cab104 in key path getter for LottieColor.cgColorValue : LottieColor+0x114 (Gener8:arm64+0x100adb104) (BuildId: 47c5cae9c1e035229d9ee05204332cfd32000000300000000700000000000f00)
    #9 0x18f3c5f54 in RawKeyPathComponent._projectReadOnly<A, B, C>(_:to:endingWith:)+0x40c (libswiftCore.dylib:arm64+0x10df54) (BuildId: fd3c87bf2e2c31d1932435c5e6a9616232000000200000000700000000000f00)
    #10 0x18f3c581c in closure #1 in KeyPath._projectReadOnly(from:)+0x22c (libswiftCore.dylib:arm64+0x10d81c) (BuildId: fd3c87bf2e2c31d1932435c5e6a9616232000000200000000700000000000f00)
    #11 0x18f3c9908 in swift_getAtKeyPath+0xa0 (libswiftCore.dylib:arm64+0x111908) (BuildId: fd3c87bf2e2c31d1932435c5e6a9616232000000200000000700000000000f00)
    #12 0x100cbba08 in implicit closure #1 in CAShapeLayer.addStrokeAnimations(for:context:)+0x364 (Gener8:arm64+0x100aeba08) (BuildId: 47c5cae9c1e035229d9ee05204332cfd32000000300000000700000000000f00)
    #13 0x100cbc750 in partial apply for implicit closure #1 in CAShapeLayer.addStrokeAnimations(for:context:)+0x10 (Gener8:arm64+0x100aec750) (BuildId: 47c5cae9c1e035229d9ee05204332cfd32000000300000000700000000000f00)
    #14 0x100c6be30 in CALayer.defaultAnimation<A, B>(for:keyframes:value:context:)+0x8c8 (Gener8:arm64+0x100a9be30) (BuildId: 47c5cae9c1e035229d9ee05204332cfd32000000300000000700000000000f00)
    #15 0x100c6a128 in CALayer.addAnimation<A, B>(for:keyframes:value:context:)+0x568 (Gener8:arm64+0x100a9a128) (BuildId: 47c5cae9c1e035229d9ee05204332cfd32000000300000000700000000000f00)
    #16 0x100cba660 in CAShapeLayer.addStrokeAnimations(for:context:)+0x1978 (Gener8:arm64+0x100aea660) (BuildId: 47c5cae9c1e035229d9ee05204332cfd32000000300000000700000000000f00)
    #17 0x100d47994 in ShapeItemLayer.setupSolidFillAnimations(shapeLayer:context:)+0x3e0c (Gener8:arm64+0x100b77994) (BuildId: 47c5cae9c1e035229d9ee05204332cfd32000000300000000700000000000f00)
    #18 0x100d433f4 in ShapeItemLayer.setupAnimations(context:)+0x858 (Gener8:arm64+0x100b733f4) (BuildId: 47c5cae9c1e035229d9ee05204332cfd32000000300000000700000000000f00)
    #19 0x100d0d514 in protocol witness for AnimationLayer.setupAnimations(context:) in conformance BaseAnimationLayer+0xf4 (Gener8:arm64+0x100b3d514) (BuildId: 47c5cae9c1e035229d9ee05204332cfd32000000300000000700000000000f00)
    #20 0x100d0b274 in BaseAnimationLayer.setupAnimations(context:)+0x53c (Gener8:arm64+0x100b3b274) (BuildId: 47c5cae9c1e035229d9ee05204332cfd32000000300000000700000000000f00)
    #21 0x100d5cf6c in GroupLayer.setupAnimations(context:)+0x2e4 (Gener8:arm64+0x100b8cf6c) (BuildId: 47c5cae9c1e035229d9ee05204332cfd32000000300000000700000000000f00)
    #22 0x100d0d514 in protocol witness for AnimationLayer.setupAnimations(context:) in conformance BaseAnimationLayer+0xf4 (Gener8:arm64+0x100b3d514) (BuildId: 47c5cae9c1e035229d9ee05204332cfd32000000300000000700000000000f00)
    #23 0x100d0b274 in BaseAnimationLayer.setupAnimations(context:)+0x53c (Gener8:arm64+0x100b3b274) (BuildId: 47c5cae9c1e035229d9ee05204332cfd32000000300000000700000000000f00)
    #24 0x100d10c3c in BaseCompositionLayer.setupChildAnimations(context:)+0x244 (Gener8:arm64+0x100b40c3c) (BuildId: 47c5cae9c1e035229d9ee05204332cfd32000000300000000700000000000f00)
    #25 0x100d0fd98 in BaseCompositionLayer.setupAnimations(context:)+0xb2c (Gener8:arm64+0x100b3fd98) (BuildId: 47c5cae9c1e035229d9ee05204332cfd32000000300000000700000000000f00)
    #26 0x100d0d514 in protocol witness for AnimationLayer.setupAnimations(context:) in conformance BaseAnimationLayer+0xf4 (Gener8:arm64+0x100b3d514) (BuildId: 47c5cae9c1e035229d9ee05204332cfd32000000300000000700000000000f00)
    #27 0x100ce2f20 in CoreAnimationLayer.setupAnimation(for:)+0x1740 (Gener8:arm64+0x100b12f20) (BuildId: 47c5cae9c1e035229d9ee05204332cfd32000000300000000700000000000f00)
    #28 0x100ce0b64 in CoreAnimationLayer.display()+0x10c8 (Gener8:arm64+0x100b10b64) (BuildId: 47c5cae9c1e035229d9ee05204332cfd32000000300000000700000000000f00)
    #29 0x100ce4004 in @objc CoreAnimationLayer.display()+0x8c (Gener8:arm64+0x100b14004) (BuildId: 47c5cae9c1e035229d9ee05204332cfd32000000300000000700000000000f00)

SUMMARY: AddressSanitizer: heap-buffer-overflow (libclang_rt.asan_iossim_dynamic.dylib:arm64+0x183cc) (BuildId: c1b3f817a02631eaacbc21ec0f6a487a32000000200000000700000000000e00) in wrap_memcpy+0x138
Shadow bytes around the buggy address:
  0x0070273f86c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0070273f86d0: fa fa fa fa fa fa fa fa fa fa fa fa fd fd fd fd
  0x0070273f86e0: fd fd fd fd fa fa fa fa fa fa fa fa fa fa fa fa
  0x0070273f86f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0070273f8700: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0070273f8710: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00[fa]
  0x0070273f8720: fa fa fa fa 00 00 00 00 00 00 00 fa fa fa fa fa
  0x0070273f8730: 00 00 00 00 00 00 00 fa fa fa fa fa 00 00 00 00
  0x0070273f8740: 00 00 00 fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0070273f8750: fa fa fa fa 00 00 00 00 00 00 00 00 fa fa fa fa
  0x0070273f8760: 00 00 00 00 00 00 00 00 fa fa fa fa fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==12762==ABORTING
AddressSanitizer report breakpoint hit. Use 'thread info -s' to get extended information about the report.
```

The stack trace ended up here: 

```
Thread 1: signal SIGABRT:

extension CGColor {
  /// Initializes a `CGColor` using the given `RGB` values
  static func rgb(_ red: CGFloat, _ green: CGFloat, _ blue: CGFloat) -> CGColor {
    CGColor(
      colorSpace: CGColorSpaceCreateDeviceRGB(),
      components: [red, green, blue])!
      .copy(alpha: 1)!
  }
}
```

**Comment by calda** [comment]
I see you're using Lottie 4.0.0 -- I'm pretty sure this is fixed in one of the more recent versions of Lottie (the current version is 4.2.0)

**Comment by jacobsapps** [comment]
Thanks @calda! Have a great day 🙏
